# Generated by Django 5.2.5 on 2025-08-28 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_alter_paciente_apellido_alter_paciente_dni_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='email',
        ),
        migrations.AddField(
            model_name='paciente',
            name='domicilio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='apellido',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
