# Generated by Django 5.2.5 on 2025-08-31 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0004_obrasocial_paciente_obra_social'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='obra_social',
        ),
        migrations.DeleteModel(
            name='ObraSocial',
        ),
        migrations.DeleteModel(
            name='Paciente',
        ),
    ]
