# Generated by Django 5.2.5 on 2025-10-31 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cajas',
            fields=[
                ('id_caja', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_hora_apertura', models.DateTimeField()),
                ('monto_apertura', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_hora_cierre', models.DateTimeField(blank=True, null=True)),
                ('monto_cierre', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estado_caja', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cajas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CarasDiente',
            fields=[
                ('id_cara', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_cara', models.CharField(max_length=30)),
                ('abreviatura', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'caras_diente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CoberturasOs',
            fields=[
                ('id_cobertura', models.BigAutoField(primary_key=True, serialize=False)),
                ('porcentaje', models.IntegerField()),
            ],
            options={
                'db_table': 'coberturas_os',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CobrosConsulta',
            fields=[
                ('id_cobro_consulta', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_metodo_cobro', models.BigIntegerField()),
                ('eliminado', models.IntegerField(blank=True, null=True)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_obra_social', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_paciente', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_hora_cobro', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cobros_consulta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetallesConsulta',
            fields=[
                ('id_detalle', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_cara', models.BigIntegerField()),
                ('eliminado', models.IntegerField(blank=True, null=True)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
                ('conformidad_paciente', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'detalles_consulta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dientes',
            fields=[
                ('id_diente', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_diente', models.CharField(blank=True, max_length=60, null=True)),
                ('eliminado', models.IntegerField(blank=True, null=True)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Egresos',
            fields=[
                ('id_egreso', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_hora_egreso', models.DateTimeField(blank=True, null=True)),
                ('descripcion_egreso', models.CharField(blank=True, max_length=100, null=True)),
                ('monto_egreso', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'egresos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id_empleado', models.BigAutoField(primary_key=True, serialize=False)),
                ('rol', models.CharField(max_length=20)),
                ('eliminado', models.IntegerField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'empleados',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadosPago',
            fields=[
                ('id_estado_pago', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_estado', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'estados_pago',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadosTurno',
            fields=[
                ('id_estado_turno', models.BigAutoField(primary_key=True, serialize=False)),
                ('estado_turno', models.CharField(max_length=20)),
                ('eliminado', models.IntegerField(blank=True, null=True)),
                ('fecha_eliminado', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'estados_turno',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FichasMedicas',
            fields=[
                ('id_ficha_medica', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateField()),
                ('observaciones', models.CharField(blank=True, max_length=150, null=True)),
                ('nro_autorizacion', models.BigIntegerField(blank=True, null=True)),
                ('nro_coseguro', models.BigIntegerField(blank=True, null=True)),
                ('eliminado', models.IntegerField(blank=True, null=True)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fichas_medicas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FichasPatologicas',
            fields=[
                ('id_ficha_patologica', models.BigAutoField(primary_key=True, serialize=False)),
                ('alergias', models.IntegerField(blank=True, null=True)),
                ('anemia', models.IntegerField(blank=True, null=True)),
                ('artritis', models.IntegerField(blank=True, null=True)),
                ('asma', models.IntegerField(blank=True, null=True)),
                ('desnutricion', models.IntegerField(blank=True, null=True)),
                ('diabetes', models.IntegerField(blank=True, null=True)),
                ('epilepsia', models.IntegerField(blank=True, null=True)),
                ('embarazo_sospecha', models.IntegerField(blank=True, null=True)),
                ('fiebre_reumatica', models.IntegerField(blank=True, null=True)),
                ('glaucoma', models.IntegerField(blank=True, null=True)),
                ('hemorragias', models.IntegerField(blank=True, null=True)),
                ('hepatitis', models.IntegerField(blank=True, null=True)),
                ('herpes', models.IntegerField(blank=True, null=True)),
                ('hipertension', models.IntegerField(blank=True, null=True)),
                ('hipotension', models.IntegerField(blank=True, null=True)),
                ('jaquecas', models.IntegerField(blank=True, null=True)),
                ('lesiones_cabeza', models.IntegerField(blank=True, null=True)),
                ('problemas_hepaticos', models.IntegerField(blank=True, null=True)),
                ('problemas_mentales', models.IntegerField(blank=True, null=True)),
                ('problemas_cardiacos', models.IntegerField(blank=True, null=True)),
                ('problemas_renales', models.IntegerField(blank=True, null=True)),
                ('problemas_tiroides', models.IntegerField(blank=True, null=True)),
                ('problemas_respiratorios', models.IntegerField(blank=True, null=True)),
                ('sinusitis', models.IntegerField(blank=True, null=True)),
                ('tuberculosis', models.IntegerField(blank=True, null=True)),
                ('tumores', models.IntegerField(blank=True, null=True)),
                ('ulceras', models.IntegerField(blank=True, null=True)),
                ('venereas', models.IntegerField(blank=True, null=True)),
                ('vih', models.IntegerField(blank=True, db_column='VIH', null=True)),
                ('portador_protesis', models.IntegerField(blank=True, null=True)),
                ('problema_periodontal', models.IntegerField(blank=True, null=True)),
                ('ortodoncia', models.IntegerField(blank=True, null=True)),
                ('mala_oclusion', models.IntegerField(blank=True, null=True)),
                ('lesion_mucosa', models.IntegerField(blank=True, null=True)),
                ('toma_medicacion', models.IntegerField(blank=True, null=True)),
                ('otra', models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                'db_table': 'fichas_patologicas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ingresos',
            fields=[
                ('id_ingreso', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_hora_ingreso', models.DateTimeField(blank=True, null=True)),
                ('descripcion_ingreso', models.CharField(blank=True, max_length=100, null=True)),
                ('monto_ingreso', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'ingresos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MetodosCobro',
            fields=[
                ('id_metodo_cobro', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo_cobro', models.CharField(max_length=30)),
                ('eliminado', models.IntegerField(blank=True, null=True)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'metodos_cobro',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ObrasSociales',
            fields=[
                ('id_obra_social', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_os', models.CharField(max_length=40)),
                ('eliminado', models.IntegerField(blank=True, null=True)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'obras_sociales',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pacientes',
            fields=[
                ('id_paciente', models.BigAutoField(primary_key=True, serialize=False)),
                ('dni_paciente', models.BigIntegerField()),
                ('nombre_paciente', models.CharField(max_length=40)),
                ('apellido_paciente', models.CharField(max_length=40)),
                ('fecha_nacimiento', models.DateField()),
                ('domicilio', models.CharField(blank=True, max_length=50, null=True)),
                ('localidad', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('correo', models.CharField(blank=True, max_length=50, null=True)),
                ('eliminado', models.IntegerField(blank=True, null=True)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pacientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PacientesXOs',
            fields=[
                ('id_paciente_os', models.BigAutoField(primary_key=True, serialize=False)),
                ('credencial_paciente', models.BigIntegerField(blank=True, null=True)),
                ('titular', models.CharField(blank=True, max_length=30, null=True)),
                ('eliminado', models.IntegerField(blank=True, null=True)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pacientes_x_os',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Parentesco',
            fields=[
                ('id_parentesco', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo_parentesco', models.CharField(max_length=30)),
                ('eliminado', models.IntegerField(blank=True, null=True)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'parentesco',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tratamientos',
            fields=[
                ('id_tratamiento', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_tratamiento', models.CharField(max_length=30)),
                ('codigo', models.CharField(max_length=20)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('eliminado', models.IntegerField(blank=True, null=True)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tratamientos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Turnos',
            fields=[
                ('id_turno', models.BigAutoField(primary_key=True, serialize=False)),
                ('asunto', models.CharField(blank=True, max_length=40, null=True)),
                ('fecha_turno', models.DateField()),
                ('hora_turno', models.TimeField()),
                ('comentario_turno', models.CharField(blank=True, max_length=60, null=True)),
                ('eliminado', models.IntegerField(blank=True, null=True)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'turnos',
                'managed': False,
            },
        ),
    ]
