# Generated by Django 5.2.1 on 2025-09-17 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cajas',
            fields=[
                ('id_caja', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_movimiento', models.DateField()),
                ('hora_movimiento', models.TimeField()),
                ('monto_movimiento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_caja', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'cajas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CarasDiente',
            fields=[
                ('id_cara', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_cara', models.CharField(max_length=30)),
                ('abreviatura', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'caras_diente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CobrosConsulta',
            fields=[
                ('id_cobro_consulta', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_metodo_cobro', models.BigIntegerField()),
                ('eliminado', models.IntegerField(blank=True, null=True)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cobros_consulta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetallesConsulta',
            fields=[
                ('id_detalle', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_cara', models.BigIntegerField()),
                ('eliminado', models.IntegerField(blank=True, null=True)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'detalles_consulta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dientes',
            fields=[
                ('id_diente', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_diente', models.CharField(blank=True, max_length=60, null=True)),
                ('eliminado', models.IntegerField(blank=True, null=True)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadosTurno',
            fields=[
                ('id_estado_turno', models.BigAutoField(primary_key=True, serialize=False)),
                ('estado_turno', models.CharField(max_length=20)),
                ('eliminado', models.IntegerField(blank=True, null=True)),
                ('fecha_eliminado', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'estados_turno',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FichasMedicas',
            fields=[
                ('id_ficha_medica', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateField()),
                ('observaciones', models.CharField(blank=True, max_length=150, null=True)),
                ('nro_autorizacion', models.BigIntegerField(blank=True, null=True)),
                ('nro_coseguro', models.BigIntegerField(blank=True, null=True)),
                ('eliminado', models.IntegerField(blank=True, null=True)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fichas_medicas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FichasPatologicas',
            fields=[
                ('id_ficha_patologica', models.BigAutoField(primary_key=True, serialize=False)),
                ('alergias', models.IntegerField(blank=True, null=True)),
                ('anemia', models.IntegerField(blank=True, null=True)),
                ('artritis', models.IntegerField(blank=True, null=True)),
                ('asma', models.IntegerField(blank=True, null=True)),
                ('desnutricion', models.IntegerField(blank=True, null=True)),
                ('diabetes', models.IntegerField(blank=True, null=True)),
                ('epilepsia', models.IntegerField(blank=True, null=True)),
                ('embarazo_sospecha', models.IntegerField(blank=True, null=True)),
                ('fiebre_reumatica', models.IntegerField(blank=True, null=True)),
                ('glaucoma', models.IntegerField(blank=True, null=True)),
                ('hemorragias', models.IntegerField(blank=True, null=True)),
                ('hepatitis', models.IntegerField(blank=True, null=True)),
                ('herpes', models.IntegerField(blank=True, null=True)),
                ('hipertension', models.IntegerField(blank=True, null=True)),
                ('hipotension', models.IntegerField(blank=True, null=True)),
                ('jaquecas', models.IntegerField(blank=True, null=True)),
                ('lesiones_cabeza', models.IntegerField(blank=True, null=True)),
                ('problemas_hepaticos', models.IntegerField(blank=True, null=True)),
                ('problemas_mentales', models.IntegerField(blank=True, null=True)),
                ('problemas_cardiacos', models.IntegerField(blank=True, null=True)),
                ('problemas_renales', models.IntegerField(blank=True, null=True)),
                ('problemas_tiroides', models.IntegerField(blank=True, null=True)),
                ('problemas_respiratorios', models.IntegerField(blank=True, null=True)),
                ('sinusitis', models.IntegerField(blank=True, null=True)),
                ('tuberculosis', models.IntegerField(blank=True, null=True)),
                ('tumores', models.IntegerField(blank=True, null=True)),
                ('ulceras', models.IntegerField(blank=True, null=True)),
                ('venereas', models.IntegerField(blank=True, null=True)),
                ('vih', models.IntegerField(blank=True, db_column='VIH', null=True)),
                ('portador_protesis', models.IntegerField(blank=True, null=True)),
                ('problema_periodontal', models.IntegerField(blank=True, null=True)),
                ('ortodoncia', models.IntegerField(blank=True, null=True)),
                ('mala_oclusion', models.IntegerField(blank=True, null=True)),
                ('lesion_mucosa', models.IntegerField(blank=True, null=True)),
                ('toma_medicacion', models.IntegerField(blank=True, null=True)),
                ('otra', models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                'db_table': 'fichas_patologicas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MetodosCobro',
            fields=[
                ('id_metodo_cobro', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo_cobro', models.CharField(max_length=30)),
                ('eliminado', models.IntegerField(blank=True, null=True)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'metodos_cobro',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MovimientosCaja',
            fields=[
                ('id_movimiento', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_movimiento', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'movimientos_caja',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ObrasSociales',
            fields=[
                ('id_obra_social', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_os', models.CharField(max_length=40)),
                ('eliminado', models.IntegerField(blank=True, null=True)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'obras_sociales',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Parentesco',
            fields=[
                ('id_parentesco', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo_parentesco', models.CharField(max_length=30)),
                ('eliminado', models.IntegerField(blank=True, null=True)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'parentesco',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tratamientos',
            fields=[
                ('id_tratamiento', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_tratamiento', models.CharField(max_length=30)),
                ('codigo', models.CharField(max_length=20)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('porcentaje', models.IntegerField()),
                ('eliminado', models.IntegerField(blank=True, null=True)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tratamientos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id_empleado', models.BigAutoField(primary_key=True, serialize=False)),
                ('rol', models.CharField(max_length=20)),
                ('eliminado', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.authuser')),
            ],
            options={
                'db_table': 'empleados',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='Caja',
        ),
        migrations.DeleteModel(
            name='Consultas',
        ),
        migrations.DeleteModel(
            name='DetalleConsulta',
        ),
        migrations.DeleteModel(
            name='DetalleServicio',
        ),
        migrations.DeleteModel(
            name='FichaMedica',
        ),
        migrations.DeleteModel(
            name='ObraSocial',
        ),
        migrations.DeleteModel(
            name='ServiciosParticulares',
        ),
    ]
