# Generated by Django 5.2.5 on 2025-08-31 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Caja',
        ),
        migrations.DeleteModel(
            name='Servicio',
        ),
    ]
